AWSTemplateFormatVersion: 2010-09-09   # Fixed format supported version 

Description: Template to create an EC2 instance and enable SSH   # Description for Cloud Formation

Parameters: 
  KeyName:
    Description: Name of SSH KeyPair
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Provide the name of an existing SSH key pair    # It will ask us to select existing key

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-082105f875acab993   # Replace with AMI available in your region
      KeyName: !Ref KeyName      # Points to KeyName parameter
      SecurityGroups:            # Points to  InstanceSecurityGroup parameter
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: Sai Instance
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: SaidemySecurityGroup
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 22             # Entrance door
        ToPort: 22               # Exit door
        CidrIp: 0.0.0.0/0

Outputs: 
  InstanceID:
    Description: The Instance ID
    Value: !Ref MyEC2Instance    # Shows Instance ID
